TELEGRAM_BOT_TOKEN = ""  # Set via GitHub Actions secret TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID = ""   # Set via GitHub Actions secret TELEGRAM_CHAT_ID

SOURCES = [
    # UA outsourcers
    "intellias",
    "eleks",
    "nix",
    "epam",
    "globallogic",
    "softserve",
    "luxoft",
    "sigma",
    "dataart",
    "playtika",
    "wix",
    "ciklum",

    "superhuman",
    "skelar",
    "squad",
    "gr8tech",
    "ajax",
    "dxc",
    "zone3000",
    "nixsolutions",
    "tieto",
    "fractal",
    "novadigital",
    "temabit",
    "evoplay",
    "headway",
    "griddynamics",
    "avenga",
    "betterme",
    "obrio",
    "allstarsit",
    "autodoc",
    "whitebit",
    "ideals",
    "genesis",
    "uklon",
    "macpaw",
    "readdle",
    "upstars",
    "dripify",
    "pmgroup",
    "galaktica",
    "capitalcom",
    "dataforest",
    "boosta",
    # UA job boards
    "dou",
    "djinni",
]
